apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      nodeSelector:
        node-role: worker   # 👈 ensures pods only run on minikube-m02
      containers:
      - name: wisecow
        image: vaibhavtg/wisecow:latest
        ports:
        - containerPort: 4499
