apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80           # Exposed port to the internet
      targetPort: 4499   # Container port
